# Generated by Django 6.0.6 on 2026-07-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Одобрено админом'),
        ),
    ]
