# Generated by Django 6.0.6 on 2026-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('dessert', 'Десерт'), ('appetizer', 'Закуска'), ('first', 'Первые блюда'), ('second', 'Вторые блюда'), ('snack', 'Перекус'), ('drink', 'Напиток'), ('salad', 'Салат'), ('soup', 'Суп'), ('main', 'Основное блюдо'), ('baking', 'Выпечка')], default='main', max_length=20, verbose_name='Категория блюда'),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение'),
        ),
    ]
