# Generated by Django 6.0.6 on 2026-08-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Калорийность (ккал)'),
        ),
        migrations.AddField(
            model_name='article',
            name='carbs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Углеводы (г)'),
        ),
        migrations.AddField(
            model_name='article',
            name='cook_time',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите время в минутах', null=True, verbose_name='Время приготовления (мин)'),
        ),
        migrations.AddField(
            model_name='article',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='easy', max_length=10, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='article',
            name='fat',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Жиры (г)'),
        ),
        migrations.AddField(
            model_name='article',
            name='protein',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Белки (г)'),
        ),
    ]
