# Generated by Django 6.0.6 on 2026-08-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_calories_article_carbs_article_cook_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientSubstitution',
        ),
    ]
