# Generated by Django 6.0.6 on 2026-08-05 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_ingredientsubstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='auto_approved',
            field=models.BooleanField(default=False, help_text='Пропущен автоматически (доверенный пользователь)', verbose_name='Автоодобрен'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Показывать комментарий на сайте', verbose_name='Одобрен'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Автофильтр пометил как спам', verbose_name='Спам'),
        ),
        migrations.AddField(
            model_name='comment',
            name='report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Жалоб'),
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Спам'), ('abuse', 'Оскорбление'), ('offtopic', 'Не по теме')], max_length=50, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата жалобы')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='blog.comment', verbose_name='Комментарий')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пожаловался')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
    ]
