# Generated by Django 6.0.6 on 2026-08-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_auto_approved_comment_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Жалоба на комментарий', 'verbose_name_plural': 'Жалобы на комментарии'},
        ),
        migrations.AlterUniqueTogether(
            name='commentreport',
            unique_together={('comment', 'reporter')},
        ),
    ]
