# Generated by Django 6.0.6 on 2026-08-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_commentreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, help_text='Вставьте ссылку на YouTube / Vimeo / Rutube / Яндекс.Видео', null=True, verbose_name='Ссылка на видео'),
        ),
    ]
