# Generated by Django 6.0.6 on 2026-08-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Калории (ккал)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Углеводы (г)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Жиры (г)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Белки (г)'),
        ),
    ]
